package com.scouttable.app.ui.common

/**
 * Nome nazione (come restituito da TheSportsDB, in inglese, o digitato in italiano dall'utente
 * nel campo libero "nazione") -> emoji bandiera, costruita dal codice ISO 3166-1 alpha-2 (coppia
 * di "regional indicator symbol", standard Unicode: A=U+1F1E6). Elenco completo di tutti gli stati
 * riconosciuti (ISO 3166-1) più alcune entità sportive comuni (Inghilterra/Scozia/Galles/Irlanda
 * del Nord, Kosovo, Taiwan, Hong Kong...), sia in inglese che in italiano: nessuna nazionalità
 * dovrebbe restare senza bandiera. Se comunque non riconosciuta non mostra nulla (nessun simbolo
 * rotto) invece di far crashare l'app.
 */
private val isoCodeByCountry: Map<String, String> = mapOf(
    // --- Europa ---
    "Italy" to "IT", "Italia" to "IT",
    "Portugal" to "PT", "Portogallo" to "PT",
    "Spain" to "ES", "Spagna" to "ES",
    "France" to "FR", "Francia" to "FR",
    "Germany" to "DE", "Germania" to "DE",
    "England" to "GB", "Inghilterra" to "GB",
    "Scotland" to "GB", "Scozia" to "GB",
    "Wales" to "GB", "Galles" to "GB",
    "Northern Ireland" to "GB", "Irlanda del Nord" to "GB",
    "United Kingdom" to "GB", "Regno Unito" to "GB", "Great Britain" to "GB", "Gran Bretagna" to "GB",
    "Ireland" to "IE", "Republic of Ireland" to "IE", "Irlanda" to "IE",
    "Netherlands" to "NL", "The Netherlands" to "NL", "Holland" to "NL", "Olanda" to "NL", "Paesi Bassi" to "NL",
    "Belgium" to "BE", "Belgio" to "BE",
    "Luxembourg" to "LU", "Lussemburgo" to "LU",
    "Switzerland" to "CH", "Svizzera" to "CH",
    "Austria" to "AT",
    "Sweden" to "SE", "Svezia" to "SE",
    "Norway" to "NO", "Norvegia" to "NO",
    "Denmark" to "DK", "Danimarca" to "DK",
    "Finland" to "FI", "Finlandia" to "FI",
    "Iceland" to "IS", "Islanda" to "IS",
    "Poland" to "PL", "Polonia" to "PL",
    "Czech Republic" to "CZ", "Czechia" to "CZ", "Repubblica Ceca" to "CZ",
    "Slovakia" to "SK", "Slovacchia" to "SK",
    "Hungary" to "HU", "Ungheria" to "HU",
    "Romania" to "RO",
    "Bulgaria" to "BG",
    "Greece" to "GR", "Grecia" to "GR",
    "Cyprus" to "CY", "Cipro" to "CY",
    "Malta" to "MT",
    "Croatia" to "HR", "Croazia" to "HR",
    "Slovenia" to "SI",
    "Serbia" to "RS",
    "Bosnia and Herzegovina" to "BA", "Bosnia ed Erzegovina" to "BA", "Bosnia" to "BA",
    "Montenegro" to "ME",
    "North Macedonia" to "MK", "Macedonia del Nord" to "MK", "Macedonia" to "MK",
    "Albania" to "AL",
    "Kosovo" to "XK",
    "Ukraine" to "UA", "Ucraina" to "UA",
    "Belarus" to "BY", "Bielorussia" to "BY",
    "Moldova" to "MD", "Moldavia" to "MD",
    "Russia" to "RU",
    "Estonia" to "EE",
    "Latvia" to "LV", "Lettonia" to "LV",
    "Lithuania" to "LT", "Lituania" to "LT",
    "Georgia" to "GE",
    "Armenia" to "AM",
    "Azerbaijan" to "AZ", "Azerbaigian" to "AZ",
    "Turkey" to "TR", "Turchia" to "TR",
    "Monaco" to "MC",
    "Andorra" to "AD",
    "San Marino" to "SM",
    "Liechtenstein" to "LI",
    "Vatican City" to "VA", "Città del Vaticano" to "VA",
    // --- Nord e Sud America ---
    "USA" to "US", "United States" to "US", "United States of America" to "US",
    "Stati Uniti" to "US", "Stati Uniti d'America" to "US",
    "Canada" to "CA",
    "Mexico" to "MX", "Messico" to "MX",
    "Brazil" to "BR", "Brasile" to "BR",
    "Argentina" to "AR",
    "Uruguay" to "UY",
    "Paraguay" to "PY",
    "Chile" to "CL", "Cile" to "CL",
    "Bolivia" to "BO",
    "Peru" to "PE", "Perù" to "PE",
    "Ecuador" to "EC",
    "Colombia" to "CO",
    "Venezuela" to "VE",
    "Guyana" to "GY",
    "Suriname" to "SR",
    "Panama" to "PA",
    "Costa Rica" to "CR",
    "Nicaragua" to "NI",
    "Honduras" to "HN",
    "El Salvador" to "SV",
    "Guatemala" to "GT",
    "Belize" to "BZ",
    "Cuba" to "CU",
    "Jamaica" to "JM", "Giamaica" to "JM",
    "Haiti" to "HT",
    "Dominican Republic" to "DO", "Repubblica Dominicana" to "DO",
    "Puerto Rico" to "PR",
    "Trinidad and Tobago" to "TT", "Trinidad e Tobago" to "TT",
    "Bahamas" to "BS",
    "Barbados" to "BB",
    // --- Asia ---
    "China" to "CN", "Cina" to "CN",
    "Japan" to "JP", "Giappone" to "JP",
    "South Korea" to "KR", "Korea Republic" to "KR", "Corea del Sud" to "KR",
    "North Korea" to "KP", "Korea DPR" to "KP", "Corea del Nord" to "KP",
    "Taiwan" to "TW", "Chinese Taipei" to "TW",
    "Hong Kong" to "HK",
    "Mongolia" to "MN",
    "India" to "IN",
    "Pakistan" to "PK",
    "Bangladesh" to "BD",
    "Sri Lanka" to "LK",
    "Nepal" to "NP",
    "Bhutan" to "BT",
    "Afghanistan" to "AF",
    "Kazakhstan" to "KZ", "Kazakistan" to "KZ",
    "Uzbekistan" to "UZ",
    "Turkmenistan" to "TM",
    "Kyrgyzstan" to "KG", "Kirghizistan" to "KG",
    "Tajikistan" to "TJ", "Tagikistan" to "TJ",
    "Thailand" to "TH", "Thailandia" to "TH",
    "Vietnam" to "VN",
    "Cambodia" to "KH", "Cambogia" to "KH",
    "Laos" to "LA",
    "Myanmar" to "MM",
    "Malaysia" to "MY", "Malesia" to "MY",
    "Singapore" to "SG",
    "Indonesia" to "ID",
    "Philippines" to "PH", "Filippine" to "PH",
    "Brunei" to "BN",
    "Timor-Leste" to "TL", "East Timor" to "TL", "Timor Est" to "TL",
    "Saudi Arabia" to "SA", "Arabia Saudita" to "SA",
    "United Arab Emirates" to "AE", "Emirati Arabi Uniti" to "AE",
    "Qatar" to "QA",
    "Kuwait" to "KW",
    "Bahrain" to "BH", "Bahrein" to "BH",
    "Oman" to "OM",
    "Yemen" to "YE",
    "Iraq" to "IQ",
    "Iran" to "IR",
    "Israel" to "IL", "Israele" to "IL",
    "Palestine" to "PS", "Palestina" to "PS",
    "Jordan" to "JO", "Giordania" to "JO",
    "Lebanon" to "LB", "Libano" to "LB",
    "Syria" to "SY", "Siria" to "SY",
    // --- Africa ---
    "Egypt" to "EG", "Egitto" to "EG",
    "Libya" to "LY", "Libia" to "LY",
    "Tunisia" to "TN",
    "Algeria" to "DZ",
    "Morocco" to "MA", "Marocco" to "MA",
    "Sudan" to "SD",
    "South Sudan" to "SS", "Sudan del Sud" to "SS",
    "Ethiopia" to "ET", "Etiopia" to "ET",
    "Eritrea" to "ER",
    "Djibouti" to "DJ", "Gibuti" to "DJ",
    "Somalia" to "SO",
    "Kenya" to "KE",
    "Uganda" to "UG",
    "Tanzania" to "TZ",
    "Rwanda" to "RW",
    "Burundi" to "BI",
    "DR Congo" to "CD", "Congo DR" to "CD", "Democratic Republic of the Congo" to "CD",
    "Repubblica Democratica del Congo" to "CD",
    "Congo" to "CG", "Republic of the Congo" to "CG",
    "Central African Republic" to "CF", "Repubblica Centrafricana" to "CF",
    "Cameroon" to "CM", "Camerun" to "CM",
    "Chad" to "TD", "Ciad" to "TD",
    "Nigeria" to "NG",
    "Niger" to "NE",
    "Benin" to "BJ",
    "Togo" to "TG",
    "Ghana" to "GH",
    "Ivory Coast" to "CI", "Cote d'Ivoire" to "CI", "Costa d'Avorio" to "CI",
    "Liberia" to "LR",
    "Sierra Leone" to "SL",
    "Guinea" to "GN",
    "Guinea-Bissau" to "GW", "Guinea Bissau" to "GW",
    "Senegal" to "SN",
    "Gambia" to "GM",
    "Mali" to "ML",
    "Burkina Faso" to "BF",
    "Mauritania" to "MR",
    "Cape Verde" to "CV", "Capo Verde" to "CV",
    "Sao Tome and Principe" to "ST", "Sao Tome e Principe" to "ST",
    "Equatorial Guinea" to "GQ", "Guinea Equatoriale" to "GQ",
    "Gabon" to "GA",
    "Angola" to "AO",
    "Zambia" to "ZM",
    "Malawi" to "MW",
    "Mozambique" to "MZ", "Mozambico" to "MZ",
    "Zimbabwe" to "ZW",
    "Botswana" to "BW",
    "Namibia" to "NA",
    "South Africa" to "ZA", "Sudafrica" to "ZA",
    "Lesotho" to "LS",
    "Eswatini" to "SZ", "Swaziland" to "SZ",
    "Madagascar" to "MG",
    "Comoros" to "KM", "Comore" to "KM",
    "Mauritius" to "MU", "Mauritius" to "MU",
    "Seychelles" to "SC",
    // --- Oceania ---
    "Australia" to "AU",
    "New Zealand" to "NZ", "Nuova Zelanda" to "NZ",
    "Fiji" to "FJ",
    "Papua New Guinea" to "PG", "Papua Nuova Guinea" to "PG",
    "Solomon Islands" to "SB", "Isole Salomone" to "SB",
    "Vanuatu" to "VU",
    "Samoa" to "WS",
    "Tonga" to "TO",
    "Kiribati" to "KI",
    "Tuvalu" to "TV",
    "Nauru" to "NR",
    "Palau" to "PW",
    "Marshall Islands" to "MH", "Isole Marshall" to "MH",
    "Micronesia" to "FM",
)

/** Elenco di tutte le nazioni riconosciute, un nome per stato (quello italiano quando presente:
 * nella mappa sopra è sempre l'ultimo elencato per ciascun codice ISO, es. "Italy"/"Italia" -> IT
 * tiene "Italia"), in ordine alfabetico: usato per il suggerimento a comparsa sul campo "Nazione"
 * in "Modifica giocatore" quando va inserita a mano perché non trovata in automatico. */
val allCountryNames: List<String> by lazy {
    val nameByCode = LinkedHashMap<String, String>()
    isoCodeByCountry.forEach { (name, code) -> nameByCode[code] = name }
    nameByCode.values.sorted()
}

fun flagEmojiFor(country: String): String {
    val trimmed = country.trim()
    // TheSportsDB usa "The Netherlands" invece di "Netherlands" (verificato in produzione, es.
    // Ruud Gullit): un fallback generico sul prefisso "The " copre anche altri casi analoghi
    // senza dover elencare ogni variante a mano.
    val code = isoCodeByCountry[trimmed]
        ?: isoCodeByCountry[trimmed.removePrefix("The ").trim()]
        ?: return ""
    return code.uppercase().map { 0x1F1E6 + (it - 'A') }
        .joinToString("") { String(Character.toChars(it)) }
}
